version: '2'

# docker-compose file to launch jenkins_master/ELK stack instead of VM.
services:

  jenkins_master:
    build:
      context: ./dockerfiles
      dockerfile: centos7_base
    container_name: jenkins_master
    entrypoint: /sbin/init
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./:/opt/toad
      - ./container_data/jenkins/data:/var/lib/jenkins/userContent
      - ./container_data/jenkins/log:/var/log/jenkins
      - ./container_data/jenkins/jobs:/etc/jenkins_jobs
    entrypoint: /sbin/init
    networks:
      default:
        ipv4_address: 172.16.238.10
    ports:
      - "8081:8081"

networks:
    default:
      ipam:
        config:
          - subnet: 172.16.238.0/24
