version: '2'

# docker-compose file to launch jenkins_master/ELK stack instead of VM.
services:
  jenkins_master:
    build: 
      context: ./dockerfiles 
      dockerfile: centos7_base
    container_name: jenkins_master
    entrypoint: /sbin/init
    privileged: true

  logstash:
    build: 
      context: ./dockerfiles 
      dockerfile: centos7_base
    container_name: logstash
    entrypoint: /sbin/init
    privileged: true

  elasticsearch:
    build: 
      context: ./dockerfiles 
      dockerfile: centos7_base
    container_name: elasticsearch
    entrypoint: /sbin/init
    privileged: true

  kibana:
    build: 
      context: ./dockerfiles 
      dockerfile: centos7_base
    container_name: kibana
    entrypoint: /sbin/init
    privileged: true
