version: '2'

# docker-compose file to launch jenkins_master/ELK stack instead of VM.
services:
  jenkins_master:
    build: 
      context: ./dockerfiles 
      dockerfile: centos7_base
    container_name: jenkins_master
    security_opt:
      - seccomp:unconfined
    volumes:
      - /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    entrypoint: /sbin/init
    ports:
      - "8080:8080"

  logstash:
    build: 
      context: ./dockerfiles 
      dockerfile: centos7_base
    container_name: logstash
    security_opt:
      - seccomp:unconfined
    volumes:
      - /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    entrypoint: /sbin/init
    ports:
      - "5044:5044"

  elasticsearch:
    build: 
      context: ./dockerfiles 
      dockerfile: centos7_base
    container_name: elasticsearch
    security_opt:
      - seccomp:unconfined
    volumes:
      - /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    entrypoint: /sbin/init
    ports:
      - "9200:9200"

  kibana:
    build: 
      context: ./dockerfiles 
      dockerfile: centos7_base
    container_name: kibana
    security_opt:
      - seccomp:unconfined
    volumes:
      - /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    entrypoint: /sbin/init
    ports:
      - "443:443"
      - "5601:5601"
