# vim: ft=ansible
---
- hosts: elasticsearch
  become: true
  tags:
    - elasticsearch
    - elk

  vars_files:
    - "{{ inventory_dir  }}/{{ vars_files_relative }}/vars/main.yml"

  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'leifmadsen.elasticsearch' }

- hosts: logstash
  become: true
  tags:
    - logstash
    - elk

  vars_files:
    - "{{ inventory_dir  }}/{{ vars_files_relative }}/vars/main.yml"

  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'geerlingguy.java' }
    - { role: 'leifmadsen.logstash' }

- hosts: kibana
  become: true
  tags:
    - kibana
    - elk

  vars_files:
    - "{{ inventory_dir  }}/{{ vars_files_relative }}/vars/main.yml"

  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'geerlingguy.nginx' }
    - { role: 'leifmadsen.kibana-4' }

  post_tasks:
    - name: Ensure libsemanage-python is installed
      yum:
        name: libsemanage-python
        state: present

    - name: Validate SELinux is enabled
      selinux:
        policy: targeted
        state: enforcing

    - name: SELinux -- Enable httpd_can_network_connect
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
