# vim: ft=ansible
---
- hosts: elasticsearch
  become: true
  tags:
    - elasticsearch
    - elk

  vars_files:
    - "{{ inventory_dir  }}/{{ vars_files_relative }}/vars/main.yml"
    - ~/.ansible/vars/toad_vars.yml

  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'leifmadsen.elasticsearch' }

- hosts: logstash
  become: true
  tags:
    - logstash
    - elk

  vars_files:
    - "{{ inventory_dir  }}/{{ vars_files_relative }}/vars/main.yml"
    - ~/.ansible/vars/toad_vars.yml

  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'geerlingguy.java' }
    - { role: 'leifmadsen.logstash' }

  post_tasks:
    - name: Add JAVA_HOME in /etc/default/logstash
      lineinfile:
        dest=/etc/default/logstash
        line='export JAVA_HOME=/usr/lib/jvm/jre'
        create=yes
      when: deploy_type is defined and deploy_type == 'docker'
      notify: restart logstash

- hosts: kibana
  become: true
  tags:
    - kibana
    - elk

  vars_files:
    - "{{ inventory_dir  }}/{{ vars_files_relative }}/vars/main.yml"
    - ~/.ansible/vars/toad_vars.yml

  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'geerlingguy.nginx' }
    - { role: 'leifmadsen.kibana-4' }

  post_tasks:
    - name: Ensure libsemanage-python is installed
      package:
        name: libsemanage-python
        state: present

    - name: Validate SELinux is enabled
      selinux:
        policy: targeted
        state: enforcing
      when: ansible_connection != 'docker'
      #when: deploy_type is not defined or deploy_type != 'docker'

    - name: SELinux -- Enable httpd_can_network_connect
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
      when: ansible_connection != 'docker'
      #when: deploy_type is not defined or deploy_type != 'docker'
