---
######################
# Deploy jobs via JJB
######################
- hosts: jenkins_master
  tags:
    - jenkins_master
    - jenkins_jobs

  vars_files:
    - "{{ inventory_dir  }}/../vars/main.yml"
    - ~/.ansible/vars/cira_vars.yml

  pre_tasks:
    - name: Validate Git is installed
      yum:
        name: git
        state: present

    - name: config get http.sslVerify
      git_config:
        name: http.sslVerify
        scope: global
      register: http_sslVerify

    - name: config http.sslVerify false
      git_config:
        name: http.sslVerify
        scope: global
        value: false
      when: http_sslVerify.config_value != 'false'

    - name: Locally clone Jenkins jobs
      git:
        repo: "{{ jenkins_job_builder_git_jobs_src }}"
        dest: "{{ jenkins_job_builder_file_jobs_src }}"
        version: master
        force: yes
        accept_hostkey: yes
      delegate_to: localhost
      changed_when: false

    - name: Create folder to store config
      file:
        path: "{{ jenkins_job_config_file_src }}"
        state: directory
        recurse: yes
        mode: "0755"
        owner: jenkins
        group: jenkins

    - name: Locally clone Jenkins job configs
      git:
        repo: "{{ jenkins_job_config_git_src }}"
        dest: "./files/nfv_jobs_config"
        version: master
        force: yes
        accept_hostkey: yes
      delegate_to: localhost
      changed_when: false

    - name: Synchronize job config to remote server
      synchronize:
        src: "./files/nfv_jobs_config/"
        dest: "{{ jenkins_job_config_file_src }}"
        archive: yes

  roles:
    - { role: 'leifmadsen.jenkins-job-builder' }

  post_tasks:
    - name: Results of JJB reload
      debug:
        var: reload_jenkins_jobs_result.stderr
      when: reload_jenkins_jobs_result is defined

