# vim: ft=ansible
---

# Deploy Jenkins Master
- hosts: jenkins_master
  tags:
    - jenkins_master

  vars_files:
    - "{{ inventory_dir  }}/../vars/main.yml"
    - ~/.ansible/vars/cira_vars.yml

  roles:
    - { role: 'franklinkim.sudo' }
    - { role: 'geerlingguy.nginx' }
    - { role: 'leifmadsen.jenkins' }

  vars:
    sudo_defaults:
      - defaults: '!requiretty'

  tasks:
    - name: Set facts for later use
      set_fact:
        jenkins_jar_location: "{{ jenkins_jar_location }}"
        jenkins_hostname: "{{ jenkins_hostname }}"
        jenkins_http_port: "{{ jenkins_http_port }}"
        jenkins_url_prefix: "{{ jenkins_url_prefix }}"
        jenkins_admin_username: "{{ jenkins_admin_username }}"
        jenkins_admin_password: "{{ jenkins_admin_password }}"

  post_tasks:
    - name: Add jenkins user to wheel group
      user:
        name: jenkins
        home: /var/lib/jenkins
        groups: wheel
        append: yes
        shell: /bin/bash

    - name: Update ownership and perms for shadow
      file:
        group: wheel
        mode: "0040"
        path: /etc/shadow

    - name: Create admin user in system
      user:
        name: "{{ jenkins_admin_username }}"
        password: "{{ jenkins_admin_password |password_hash('sha512')}}"
        shell: /bin/bash

    - name: Validate SELinux is enabled
      selinux:
        policy: targeted
        state: enforcing

    - name: SELinux -- Enable httpd_can_network_connect
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

    - name: Copy Jenkins Nginx Configuration
      template:
        src: jenkins_master-vhost.conf.j2
        dest: /etc/nginx/conf.d/jenkins_master.conf
        owner: root
        group: root
        mode: "0644"
      notify: restart nginx

    - name: Automate jenkins configuration
      template:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        owner: "{{item.owner}}"
        group: "{{item.group}}"
        mode: "{{item.mode}}"
      notify: restart jenkins
      with_items:
        - src: jenkins_config/config.xml.j2
          dest: /var/lib/jenkins/config.xml
          owner: jenkins
          group: jenkins
          mode: "0644"
        - src: jenkins_config/credentials.xml.j2
          dest: /var/lib/jenkins/credentials.xml
          owner: jenkins
          group: jenkins
          mode: "0644"
        - src: jenkins_config/be.certipost.hudson.plugin.SCPRepositoryPublisher.xml.j2
          dest: /var/lib/jenkins/be.certipost.hudson.plugin.SCPRepositoryPublisher.xml
          owner: jenkins
          group: jenkins
          mode: "0644"

    - name: Create Jenkins user .ssh directory
      file:
        path: "{{ jenkins_master_ssh_directory }}"
        state: directory
        owner: jenkins
        group: jenkins
        mode: "0700"

    - name: Generate SSH keypair
      command: ssh-keygen -N '' -f {{ jenkins_master_ssh_directory }}/id_rsa
      args:
        creates: "{{ jenkins_master_ssh_directory }}/id_rsa"

    - name: Validate correct permissions on SSH keys
      file:
        path: "{{ jenkins_master_ssh_directory }}/{{ item.filename }}"
        owner: jenkins
        group: jenkins
        mode: "{{ item.mode }}"
      with_items:
        - { filename: id_rsa, mode: "0400" }
        - { filename: id_rsa.pub, mode: "0664" }

    - name: Get public SSH key contents
      command: cat {{ jenkins_master_ssh_directory }}/id_rsa.pub
      register: jenkins_master_pub
      tags:
        # Skip ANSIBLE0012. We want to validate our public key is copied over.
        - skip_ansible_lint

    - name: Allow SSH into localhost on the master
      authorized_key:
        user: jenkins
        key: "{{ jenkins_master_pub.stdout }}"

    - name: Get localhost SSH fingerprint
      command: ssh-keyscan -4 -t ecdsa-sha2-nistp256 127.0.0.1
      register: jenkins_master_ssh_fingerprint
      tags:
        - skip_ansible_lint

    - name: Add localhost SSH fingerprint to known_hosts
      become_user: jenkins
      known_hosts:
        name: 127.0.0.1
        key: "{{ jenkins_master_ssh_fingerprint.stdout }}"
        state: present

    - name: Create slave results directory
      file:
        path: "{{ jenkins_master_results_directory }}"
        state: directory
        owner: jenkins
        group: jenkins
        mode: "0700"

# Deploy jobs via JJB
- hosts: jenkins_master
  tags:
    - jenkins_master

  vars_files:
    - "{{ inventory_dir  }}/../vars/main.yml"
    - ~/.ansible/vars/cira_vars.yml

  pre_tasks:
    - name: Validate Git is installed
      yum:
        name: git
        state: present

    - name: config get http.sslVerify
      git_config:
        name: http.sslVerify
        scope: global
      register: http_sslVerify

    - name: config http.sslVerify false
      git_config:
        name: http.sslVerify
        scope: global
        value: false
      when: http_sslVerify.config_value != 'false'

    - name: Locally clone Jenkins jobs
      git:
        repo: "{{ jenkins_job_builder_git_jobs_src }}"
        dest: "{{ jenkins_job_builder_file_jobs_src }}"
        version: master
        force: yes
      delegate_to: localhost
      changed_when: false

    - name: Create folder to store config
      file:
        path: "{{ jenkins_job_config_file_src }}"
        state: directory
        recurse: yes
        mode: "0755"
        owner: jenkins
        group: jenkins

    - name: Locally clone Jenkins job configs
      git:
        repo: "{{ jenkins_job_config_git_src }}"
        dest: "./files/nfv_jobs_config"
        version: master
        force: yes
      delegate_to: localhost
      changed_when: false

    - name: Synchronize job config to remote server
      synchronize:
        src: "./files/nfv_jobs_config/"
        dest: "{{ jenkins_job_config_file_src }}"
        archive: yes

  roles:
    - { role: 'leifmadsen.jenkins-job-builder' }

  post_tasks:
    - name: Results of JJB reload
      debug:
        var: reload_jenkins_jobs_result.stderr
      when: reload_jenkins_jobs_result is defined

# Deploy Jenkins Slave
- hosts: jenkins_slave
  become: yes
  roles:
    - { role: 'franklinkim.sudo' }
    - { role: 'geerlingguy.java' }

  vars_files:
    - "{{ inventory_dir  }}/../vars/main.yml"
    - ~/.ansible/vars/cira_vars.yml

  vars:
    sudo_defaults:
      - defaults: '!requiretty'
    sudo_users:
      - name: 'jenkins'
        nopasswd: yes

  tags:
    - jenkins_slave

  pre_tasks:
    - name: Ensure libselinux-python is installed
      yum:
        name: libselinux-python
        state: present

    - name: Create jenkins user
      user:
        name: jenkins
        comment: "Jenkins Slave User"
        generate_ssh_key: yes

  tasks:
    - name: Validate Git is installed
      yum:
        name: git
        state: present

    # TODO: this is a work around because I haven't figured out how to properly
    #       access the registered hostvars on the jenkins_master.
    - name: Set fact containing the jenkins_master SSH public key
      become: no
      ignore_errors: yes
      set_fact:
        jenkins_master_pub: "{{ hostvars[item].jenkins_master_pub.stdout }}"
      with_inventory_hostnames: jenkins_master
      tags:
        # Skip ANSIBLE0015. Use of bare variable jenkins_master is correct.
        - skip_ansible_lint

    - name: Get contents of jenkins public key
      command: cat /home/jenkins/.ssh/id_rsa.pub
      register: jenkins_slave_pub
      tags:
        # Skip ANSIBLE0012. We want to validate our public key is copied over.
        - skip_ansible_lint

    - name: Add authorized host keys to authorized_keys
      become_user: jenkins
      ignore_errors: yes
      authorized_key:
        user: jenkins
        key: "{{ item }}"
      with_items:
      - "{{ jenkins_master_pub }}"
      - "{{ jenkins_slave_pub.stdout }}"

    - name: Add jenkins public key to local root user
      become: yes
      authorized_key:
        user: root
        key: "{{ jenkins_slave_pub.stdout }}"

    - name: Get SSH fingerprint of slave
      shell: ssh-keyscan -4 -t ecdsa-sha2-nistp256 $HOSTNAME
      register: jenkins_slave_ssh_fingerprint
      tags:
        - skip_ansible_lint

    - name: Get hostname of slave
      shell: echo $HOSTNAME
      register: jenkins_slave_ssh_hostname
      tags:
        - skip_ansible_lint

- hosts: jenkins_master
  become: yes
  tags:
    - jenkins_slave

  vars_files:
    - ~/.ansible/vars/cira_vars.yml

  tasks:
    - name: Set fact containing the slave SSH fingerprint
      become: no
      ignore_errors: yes
      set_fact:
        jenkins_slave_ssh_hostname: "{{ hostvars[item].jenkins_slave_ssh_hostname.stdout }}"
        jenkins_slave_ssh_fingerprint: "{{ hostvars[item].jenkins_slave_ssh_fingerprint.stdout }}"
      with_inventory_hostnames: jenkins_slave
      tags:
        # Skip ANSIBLE0015. Use of bare variable jenkins_master is correct.
        - skip_ansible_lint

    - name: Add Jenkins slave SSH fingerprint to known hosts
      become_user: jenkins
      known_hosts:
        name: "{{ jenkins_slave_ssh_hostname }}"
        key: "{{ jenkins_slave_ssh_fingerprint }}"
        state: present

    # TODO: This is kind of hacky since it doesn't deal with multiple jenkins
    #       slaves. We'll need to circle back and make this deal with lists.
    - name: Check if our node already exists
      ignore_errors: true
      command: >
        java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/
        get-node {{ slave_name }}
        --username {{ jenkins_admin_username }}
        --password {{ jenkins_admin_password }}
      register: jenkins_cli_get_node
      when: slave_name is defined

    - name: Deploy template for Jenkins slave node
      template:
        src: jenkins_slave.j2
        dest: /tmp/jenkins_slave_{{ slave_name }}.tmpl
      when: jenkins_cli_get_node.stderr is defined and jenkins_cli_get_node.stderr != ""

    - name: Add Jenkins slave node to the master
      shell: >
        java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/
        create-node {{ slave_name }}
        --username {{ jenkins_admin_username }}
        --password {{ jenkins_admin_password }} < /tmp/jenkins_slave_{{ slave_name }}.tmpl
      when: jenkins_cli_get_node.stderr is defined and jenkins_cli_get_node.stderr != ""

    - name: Remove template for Jenkins slave node
      file:
        name: /tmp/jenkins_slave_{{ slave_name }}.tmpl
        state: absent
      when: slave_name is defined and jenkins_cli_get_node.stderr != ""
