---
- src: geerlingguy.repo-epel
- src: https://github.com/leifmadsen/ansible-role-elasticsearch.git
  version: master
  name: leifmadsen.elasticsearch
- src: https://github.com/leifmadsen/ansible-role-logstash.git
  version: master
  name: leifmadsen.logstash
- src: geerlingguy.nginx
- src: leifmadsen.kibana-4
- src: https://github.com/leifmadsen/ansible-role-jenkins.git
  version: master
  name: leifmadsen.jenkins
- src: https://github.com/leifmadsen/ansible-role-jenkins-job-builder.git
  version: master
  name: leifmadsen.jenkins-job-builder
