# main.yml
---

- include: openstack.yml

- hosts: all:!localhost
  become: yes
  vars_files:
    - vars/main.yml
    - ~/.ansible/vars/elk_vars.yml

- hosts: elasticsearch
  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'leifmadsen.elasticsearch' }

- hosts: logstash
  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'leifmadsen.logstash' }

- hosts: kibana
  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'geerlingguy.nginx' }
    - { role: 'leifmadsen.kibana-4' }

  post_tasks:
    - name: Validate SELinux is enabled
      selinux:
        policy: targeted
        state: enforcing

    - name: SELinux -- Enable httpd_can_network_connect
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
