# main.yml
---

# Deploy to OpenStack Servers
- include: openstack.yml
  when: use_openstack_deploy

- hosts: elasticsearch
  vars_files:
    - vars/main.yml

  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'leifmadsen.elasticsearch' }

- hosts: logstash
  vars_files:
    - vars/main.yml

  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'leifmadsen.logstash' }

- hosts: kibana
  vars_files:
    - vars/main.yml
  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'geerlingguy.nginx' }
    - { role: 'leifmadsen.kibana-4' }

  post_tasks:
    - name: Validate SELinux is enabled
      selinux:
        policy: targeted
        state: enforcing

    - name: SELinux -- Enable httpd_can_network_connect
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
