# vim: set ft=ansible
# main.yml
---

# Deploy to OpenStack Servers
- include: openstack.yml
  when: use_openstack_deploy

# Deploy Jenkins Master and Slave
- include: jenkins.yml

# Include the ELK stack playbook
- include: elk.yml

# Include FileBeat setup
- include: filebeat.yml

# Section that provides post-installation information
- hosts: kibana
  tags:
    - kibana
    - elk

  post_tasks:
    - name: Where is Kibana located?
      debug:
        msg: "Kibana can be reached at http://{{hostvars['kibana']['ansible_host']}}:5601/"

- hosts: jenkins_master
  tags:
    - jenkins_master

  post_tasks:
    - name: Where is Jenkins Master located?
      debug:
        msg: "Jenkins Master can be reached at http://{{hostvars['jenkins_master']['ansible_host']}}:8080/"
