# vim: set ft=ansible
# main.yml
---

# Deploy to OpenStack Servers
- include: openstack.yml
  when: use_openstack_deploy

- hosts: jenkins_master
  vars_files:
    - vars/main.yml
    - ~/.ansible/vars/cira_vars.yml

  pre_tasks:
    - include: requiretty.yml

    - name: Locally clone Jenkins jobs
      git:
        repo: "{{ jenkins_job_builder_git_jobs_src }}"
        dest: "{{ jenkins_job_builder_file_jobs_src }}"
        version: HEAD
        force: yes
      delegate_to: localhost
      changed_when: false

    - name: Create folder to store config
      file:
        path={{ jenkins_job_config_file_src }}
        state=directory
        mode=0755
        owner=jenkins
        group=jenkins

    - name: Locally clone Jenkins job configs
      git:
        repo: "{{ jenkins_job_config_git_src }}"
        dest: "./files/nfv_jobs_config"
        version: HEAD
        force: yes
      delegate_to: localhost
      changed_when: false

    - name: Synchronize job config to remote server
      synchronize:
        src="./files/nfv_jobs_config/"
        dest="{{ jenkins_job_config_file_src }}"
        archive=yes

  roles:
    - { role: 'geerlingguy.nginx' }
    - { role: 'geerlingguy.jenkins' }
    - { role: 'leifmadsen.jenkins-job-builder' }

  post_tasks:
    - name: Results of JJB reload
      debug:
        var: reload_jenkins_jobs_result.stderr
      when: reload_jenkins_jobs_result is defined

    - name: Validate SELinux is enabled
      selinux:
        policy: targeted
        state: enforcing

    - name: SELinux -- Enable httpd_can_network_connect
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

    - name: Copy Jenkins Nginx Configuration
      template:
        src: jenkins_master-vhost.conf.j2
        dest: /etc/nginx/conf.d/jenkins_master.conf
        owner: root
        group: root
        mode: 0644
      notify: restart nginx

    - block:
        - name: Bring jenkins configuration
          template:
          src: jenkins_config/config.xml.j2
          dest: /var/lib/jenkins/config.xml
          owner: jenkins
          group: jenkins
          mode: 0644

        - name: Autoconfigure jenkins plugins
          template:
          src: jenkins_config/be.certipost.hudson.plugin.SCPRepositoryPublisher.xml.j2
          dest: /var/lib/jenkins/be.certipost.hudson.plugin.SCPRepositoryPublisher.xml
          owner: jenkins
          group: jenkins
          mode: 0644
      notify: restart jenkins

- hosts: elasticsearch
  vars_files:
    - vars/main.yml

  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'leifmadsen.elasticsearch' }

- hosts: logstash
  vars_files:
    - vars/main.yml

  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'leifmadsen.logstash' }

- hosts: kibana
  vars_files:
    - vars/main.yml
  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'geerlingguy.nginx' }
    - { role: 'leifmadsen.kibana-4' }

  post_tasks:
    - name: Validate SELinux is enabled
      selinux:
        policy: targeted
        state: enforcing

    - name: SELinux -- Enable httpd_can_network_connect
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

- hosts: kibana
  post_tasks:
    - name: Where is Kibana located?
      debug:
        msg: "Kibana can be reached at http://{{hostvars['kibana']['ansible_host']}}"

- hosts: jenkins_master
  post_tasks:
    - name: Where is Jenkins Master located?
      debug:
        msg: "Jenkins Master can be reached at http://{{hostvars['jenkins_master']['ansible_host']}}"
