# vim: set ft=ansible
# main.yml
---

# Deploy to OpenStack Servers
- include: openstack.yml
  when: use_openstack_deploy

- hosts: jenkins_master
  vars_files:
    - vars/main.yml
    - ~/.ansible/vars/cira_vars.yml

  pre_tasks:
    - name: Locally clone Jenkins jobs
      git:
        repo: "{{ jenkins_job_builder_git_jobs_src }}"
        dest: "{{ jenkins_job_builder_file_jobs_src }}"
        version: HEAD
        force: yes
      delegate_to: localhost
      changed_when: false

  roles:
    - { role: 'geerlingguy.nginx' }
    - { role: 'geerlingguy.jenkins' }
    - { role: 'leifmadsen.jenkins-job-builder' }

  post_tasks:
    - name: Validate SELinux is enabled
      selinux:
        policy: targeted
        state: enforcing

    - name: SELinux -- Enable httpd_can_network_connect
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

    - name: Copy Jenkins Nginx Configuration
      template:
        src: jenkins_master-vhost.conf.j2
        dest: /etc/nginx/conf.d/jenkins_master.conf
        owner: root
        group: root
        mode: 0644
      notify: restart nginx

- hosts: elasticsearch
  vars_files:
    - vars/main.yml

  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'leifmadsen.elasticsearch' }

- hosts: logstash
  vars_files:
    - vars/main.yml

  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'leifmadsen.logstash' }

- hosts: kibana
  vars_files:
    - vars/main.yml
  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'geerlingguy.nginx' }
    - { role: 'leifmadsen.kibana-4' }

  post_tasks:
    - name: Validate SELinux is enabled
      selinux:
        policy: targeted
        state: enforcing

    - name: SELinux -- Enable httpd_can_network_connect
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

- hosts: all
  post_tasks:
    - name: Where is Kibana located?
      debug:
        msg: "Kibana can be reached at http://{{hostvars['kibana']['ansible_host']}}"

    - name: Where is Jenkins Master located?
      debug:
        msg: "Jenkins Master can be reached at http://{{hostvars['jenkins_master']['ansible_host']}}"
