# main.yml
---
- hosts: elk
  become: yes
  vars_files:
    - vars/main.yml

  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'geerlingguy.elasticsearch' }
    - { role: 'leifmadsen.logstash' }
    - { role: 'geerlingguy.nginx' }
    - { role: 'leifmadsen.kibana-4',  }
